# Use the official Python Alpine image as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /b15_clustering_front

# Copy the current directory contents into the container at /usr/src/app
COPY /front .

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt


# Run app.py when the container launches
CMD ["python", "api.py"]