on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az container delete --name soriyab15fastfront --resource-group grsoriyab15 --yes
          az container create --resource-group grsoriyab15 --file deploy-aci.yaml --registry-username soriyab15 --registry-password edC42Xjd/1JKL4O0dn+Xj7IF8n2o9kCbrse0ySPuZh+ACRDO0lA0
