on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    # Match and replace by Regex in the 'deploy.toml' file
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "password.registry"
        replace: ${{ secrets.AZURE_REGISTRY_SECRET }}
        regex: true
        include: 'deploy-aci.yaml'
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az container delete --name soriyab15fastfront --resource-group grsoriyab15 --yes
          az container create --resource-group grsoriyab15 --file deploy-aci.yaml
